cacheFolder: ./.yarn/cache

enableGlobalCache: false

nodeLinker: node-modules

npmRegistryServer: "https://artifactory.acorn.cirrostratus.org/artifactory/api/npm/npms/"

supportedArchitectures:
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-4.12.0.cjs
