enableGlobalCache: false

npmRegistryServer: "https://artifactory.acorn.cirrostratus.org/artifactory/api/npm/npms/"

nodeLinker: node-modules
cacheFolder: "./.yarn/cache"

supportedArchitectures:
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-4.9.3.cjs