kind: RouteTable
apiVersion: gateway.solo.io/v1
metadata:
  labels:
    apiGroup: test-pep.jstor.org
  name: jaip-backend-route
  namespace: sequoia
spec:
  routes:
    - matchers:
        - prefix: /api
      routeAction:
        single:
          upstream:
            name: jaip-backend
            namespace: sequoia
      options:
        timeout: "30s"
  weight: 0

